services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - network_

  courses:
    build: .
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/users
      - PYTHONPATH=/src
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - network_

networks:
  network_:
    driver: bridge

volumes:
  mongo_data: